import { InstansiItem } from '../types';
import { SAMPLE_SSCASN_DATA } from './sampleData';

export const INITIAL_INSTANSI_LIST: InstansiItem[] = [
  {
    id: 'instansi-pemkab-jember',
    nama: 'Pemerintah Kabupaten Jember',
    kode: '6512',
    kategori: 'pemkab_pemkot',
    provinsi: 'Jawa Timur',
    status: 'terdaftar',
    tahun: '2024',
    updatedAt: new Date().toISOString(),
    parsedData: SAMPLE_SSCASN_DATA,
    pdfFileName: 'HASIL_INTEGRASI_SKD_SKB_JEMBER_2024.pdf',
    notes: 'Data hasil integrasi SKD & SKB CASN Pemkab Jember 2024 (2 Formasi terdeteksi)',
  },
  {
    id: 'instansi-kemenkumham',
    nama: 'Kementerian Hukum dan Hak Asasi Manusia',
    kode: '4001',
    kategori: 'kementerian',
    status: 'terdaftar',
    tahun: '2024',
    updatedAt: new Date().toISOString(),
    parsedData: {
      meta: {
        docTitle: 'PANITIA SELEKSI NASIONAL PENGADAAN CASN - KEMENKUMHAM 2024',
        tahun: '2024',
        parsedAt: new Date().toISOString(),
        sourceType: 'sample',
        fileName: 'HASIL_INTEGRASI_KEMENKUMHAM_2024.pdf',
        totalFormasiCount: 2,
        totalPesertaCount: 8,
      },
      formasiList: [
        {
          id: 'kemenkumham-1',
          header: {
            instansi: '4001 - Kementerian Hukum dan HAM',
            kodeInstansi: '4001',
            namaInstansi: 'Kementerian Hukum dan HAM',
            jabatanFormasi: 'JF001102 - ANALIS HUKUM AHLI PERTAMA',
            kodeJabatan: 'JF001102',
            namaJabatan: 'ANALIS HUKUM AHLI PERTAMA',
            lokasiFormasi: 'SEKRETARIAT JENDERAL KEMENKUMHAM RI',
            kodeLokasi: '4001001',
            namaLokasi: 'SEKRETARIAT JENDERAL KEMENKUMHAM RI',
            jenisFormasi: 'UMUM',
            kodeJenisFormasi: '1',
            namaJenisFormasi: 'UMUM',
            pendidikan: 'S-1 HUKUM',
            jumlahKuota: 3,
          },
          pesertaList: [
            {
              no: 1,
              noPeserta: '24400120110000012',
              nama: 'FACHRI RAMADHAN SH',
              tanggalLahir: '14 Mei 1997',
              pendidikan: 'S-1 HUKUM',
              ipk: 3.82,
              twk: 115,
              tiu: 155,
              tkp: 198,
              totalSkd: 468,
              skorSkd: 34.036,
              skb: 78.5,
              skorSkb: 47.1,
              nilaiAkhir: 81.136,
              keterangan: 'P/L',
            },
            {
              no: 2,
              noPeserta: '24400120120000088',
              nama: 'ANISA PRATIWI SH',
              tanggalLahir: '22 Agustus 1999',
              pendidikan: 'S-1 HUKUM',
              ipk: 3.75,
              twk: 110,
              tiu: 140,
              tkp: 192,
              totalSkd: 442,
              skorSkd: 32.145,
              skb: 74.0,
              skorSkb: 44.4,
              nilaiAkhir: 76.545,
              keterangan: 'P/L',
            },
            {
              no: 3,
              noPeserta: '24400120110000142',
              nama: 'BAMBANG KUSUMA SH',
              tanggalLahir: '10 Januari 1996',
              pendidikan: 'S-1 HUKUM',
              ipk: 3.6,
              twk: 105,
              tiu: 135,
              tkp: 188,
              totalSkd: 428,
              skorSkd: 31.127,
              skb: 71.0,
              skorSkb: 42.6,
              nilaiAkhir: 73.727,
              keterangan: 'P/L',
            },
            {
              no: 4,
              noPeserta: '24400120120000211',
              nama: 'CITRA LESTARI SH',
              tanggalLahir: '03 November 1998',
              pendidikan: 'S-1 HUKUM',
              ipk: 3.55,
              twk: 95,
              tiu: 125,
              tkp: 185,
              totalSkd: 405,
              skorSkd: 29.455,
              skb: 65.0,
              skorSkb: 39.0,
              nilaiAkhir: 68.455,
              keterangan: 'TL',
            },
          ],
          verification: {
            isValid: true,
            scoreAccuracyPercent: 100,
            totalRecords: 4,
            discrepanciesCount: 0,
            passedCount: 3,
            failedCount: 1,
            discrepanciesList: [],
          },
        },
        {
          id: 'kemenkumham-2',
          header: {
            instansi: '4001 - Kementerian Hukum dan HAM',
            kodeInstansi: '4001',
            namaInstansi: 'Kementerian Hukum dan HAM',
            jabatanFormasi: 'JF001108 - PEMERIKSA KEIMIGRASIAN PERTAMA',
            kodeJabatan: 'JF001108',
            namaJabatan: 'PEMERIKSA KEIMIGRASIAN PERTAMA',
            lokasiFormasi: 'DIREKTORAT JENDERAL IMIGRASI',
            kodeLokasi: '4001004',
            namaLokasi: 'DIREKTORAT JENDERAL IMIGRASI',
            jenisFormasi: 'UMUM',
            kodeJenisFormasi: '1',
            namaJenisFormasi: 'UMUM',
            pendidikan: 'S-1 HUBUNGAN INTERNASIONAL / S-1 SASTRA INGGRIS',
            jumlahKuota: 2,
          },
          pesertaList: [
            {
              no: 1,
              noPeserta: '24400120110000305',
              nama: 'DENNY ARDIANSYAH',
              tanggalLahir: '17 Juli 1998',
              pendidikan: 'S-1 HUBUNGAN INTERNASIONAL',
              ipk: 3.88,
              twk: 120,
              tiu: 150,
              tkp: 201,
              totalSkd: 471,
              skorSkd: 34.255,
              skb: 80.0,
              skorSkb: 48.0,
              nilaiAkhir: 82.255,
              keterangan: 'P/L',
            },
            {
              no: 2,
              noPeserta: '24400120120000399',
              nama: 'EKA SURYANINGSIH',
              tanggalLahir: '05 April 2000',
              pendidikan: 'S-1 SASTRA INGGRIS',
              ipk: 3.7,
              twk: 115,
              tiu: 140,
              tkp: 190,
              totalSkd: 445,
              skorSkd: 32.364,
              skb: 72.0,
              skorSkb: 43.2,
              nilaiAkhir: 75.564,
              keterangan: 'P/L',
            },
            {
              no: 3,
              noPeserta: '24400120110000412',
              nama: 'FARHAN MAULANA',
              tanggalLahir: '12 Des 1997',
              pendidikan: 'S-1 HUBUNGAN INTERNASIONAL',
              ipk: 3.4,
              twk: 100,
              tiu: 130,
              tkp: 180,
              totalSkd: 410,
              skorSkd: 29.818,
              skb: 62.0,
              skorSkb: 37.2,
              nilaiAkhir: 67.018,
              keterangan: 'TL',
            },
            {
              no: 4,
              noPeserta: '24400120120000488',
              nama: 'GITA SAFITRI',
              tanggalLahir: '19 Sep 1999',
              pendidikan: 'S-1 SASTRA INGGRIS',
              ipk: 3.65,
              twk: 95,
              tiu: 120,
              tkp: 185,
              totalSkd: 400,
              skorSkd: 29.091,
              skb: 59.0,
              skorSkb: 35.4,
              nilaiAkhir: 64.491,
              keterangan: 'TL',
            },
          ],
          verification: {
            isValid: true,
            scoreAccuracyPercent: 100,
            totalRecords: 4,
            discrepanciesCount: 0,
            passedCount: 2,
            failedCount: 2,
            discrepanciesList: [],
          },
        },
      ],
      header: {
        instansi: '4001 - Kementerian Hukum dan HAM',
        jabatanFormasi: '2 Formasi Terdeteksi',
        lokasiFormasi: 'Berbagai Lokasi Kemenkumham',
        jenisFormasi: '1 - UMUM',
        pendidikan: 'S-1 HUKUM / S-1 HI / S-1 SASTRA INGGRIS',
        jumlahKuota: 5,
      },
      pesertaList: [],
      verification: {
        isValid: true,
        scoreAccuracyPercent: 100,
        totalRecords: 8,
        discrepanciesCount: 0,
        passedCount: 5,
        failedCount: 3,
        discrepanciesList: [],
      },
    },
    pdfFileName: 'HASIL_INTEGRASI_KEMENKUMHAM_2024.pdf',
    notes: 'Kementerian Hukum & HAM Pusat - Formasi Analis Hukum & Pemeriksa Keimigrasian',
  },
  {
    id: 'instansi-kemenkeu',
    nama: 'Kementerian Keuangan',
    kode: '3001',
    kategori: 'kementerian',
    status: 'terdaftar',
    tahun: '2024',
    updatedAt: new Date().toISOString(),
    parsedData: {
      meta: {
        docTitle: 'PANITIA SELEKSI NASIONAL PENGADAAN CASN - KEMENKEU 2024',
        tahun: '2024',
        parsedAt: new Date().toISOString(),
        sourceType: 'sample',
        fileName: 'HASIL_INTEGRASI_KEMENKEU_2024.pdf',
        totalFormasiCount: 1,
        totalPesertaCount: 5,
      },
      formasiList: [
        {
          id: 'kemenkeu-1',
          header: {
            instansi: '3001 - Kementerian Keuangan',
            kodeInstansi: '3001',
            namaInstansi: 'Kementerian Keuangan',
            jabatanFormasi: 'JF002010 - ANALIS PERBENDAHARAAN ANGGARAN',
            kodeJabatan: 'JF002010',
            namaJabatan: 'ANALIS PERBENDAHARAAN ANGGARAN',
            lokasiFormasi: 'DIREKTORAT JENDERAL PERBENDAHARAAN KEMENKEU',
            kodeLokasi: '3001002',
            namaLokasi: 'DIREKTORAT JENDERAL PERBENDAHARAAN KEMENKEU',
            jenisFormasi: '1 - UMUM',
            kodeJenisFormasi: '1',
            namaJenisFormasi: 'UMUM',
            pendidikan: 'S-1 AKUNTANSI / S-1 MANAJEMEN / S-1 EKONOMI',
            jumlahKuota: 2,
          },
          pesertaList: [
            {
              no: 1,
              noPeserta: '24300120110000001',
              nama: 'HENDRA WIJAYA SE',
              tanggalLahir: '08 Jan 1996',
              pendidikan: 'S-1 AKUNTANSI',
              ipk: 3.92,
              twk: 125,
              tiu: 160,
              tkp: 205,
              totalSkd: 490,
              skorSkd: 35.636,
              skb: 85.0,
              skorSkb: 51.0,
              nilaiAkhir: 86.636,
              keterangan: 'P/L',
            },
            {
              no: 2,
              noPeserta: '24300120120000005',
              nama: 'INDAH LESTARI SE',
              tanggalLahir: '14 Feb 1998',
              pendidikan: 'S-1 AKUNTANSI',
              ipk: 3.8,
              twk: 115,
              tiu: 150,
              tkp: 195,
              totalSkd: 460,
              skorSkd: 33.455,
              skb: 79.0,
              skorSkb: 47.4,
              nilaiAkhir: 80.855,
              keterangan: 'P/L',
            },
            {
              no: 3,
              noPeserta: '24300120110000018',
              nama: 'JOKO SUSILO SE',
              tanggalLahir: '20 Mar 1997',
              pendidikan: 'S-1 EKONOMI',
              ipk: 3.65,
              twk: 110,
              tiu: 140,
              tkp: 190,
              totalSkd: 440,
              skorSkd: 32.0,
              skb: 70.0,
              skorSkb: 42.0,
              nilaiAkhir: 74.0,
              keterangan: 'TL',
            },
          ],
          verification: {
            isValid: true,
            scoreAccuracyPercent: 100,
            totalRecords: 3,
            discrepanciesCount: 0,
            passedCount: 2,
            failedCount: 1,
            discrepanciesList: [],
          },
        },
      ],
      header: {
        instansi: '3001 - Kementerian Keuangan',
        jabatanFormasi: 'ANALIS PERBENDAHARAAN ANGGARAN',
        lokasiFormasi: 'DJPb Kemenkeu',
        jenisFormasi: '1 - UMUM',
        pendidikan: 'S-1 AKUNTANSI / S-1 MANAJEMEN / S-1 EKONOMI',
        jumlahKuota: 2,
      },
      pesertaList: [],
      verification: {
        isValid: true,
        scoreAccuracyPercent: 100,
        totalRecords: 3,
        discrepanciesCount: 0,
        passedCount: 2,
        failedCount: 1,
        discrepanciesList: [],
      },
    },
    pdfFileName: 'HASIL_INTEGRASI_KEMENKEU_2024.pdf',
    notes: 'Kementerian Keuangan Pusat',
  },
  {
    id: 'instansi-pemprov-jatim',
    nama: 'Pemerintah Provinsi Jawa Timur',
    kode: '6500',
    kategori: 'pemprov',
    provinsi: 'Jawa Timur',
    status: 'terdaftar',
    tahun: '2024',
    updatedAt: new Date().toISOString(),
    notes: 'Pemerintah Provinsi Jawa Timur',
  },
  {
    id: 'instansi-kejaksaan',
    nama: 'Kejaksaan Agung Republik Indonesia',
    kode: '1002',
    kategori: 'lembaga',
    status: 'terdaftar',
    tahun: '2024',
    updatedAt: new Date().toISOString(),
    notes: 'Kejaksaan RI - Penuntut Umum & Pengelola Penanganan Perkara',
  },
  {
    id: 'instansi-kemendikbud',
    nama: 'Kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi',
    kode: '4005',
    kategori: 'kementerian',
    status: 'terdaftar',
    tahun: '2024',
    updatedAt: new Date().toISOString(),
    notes: 'Kemendikbudristek - Formasi Dosen & Tenaga Kependidikan',
  },
  {
    id: 'instansi-kemenkes',
    nama: 'Kementerian Kesehatan',
    kode: '4003',
    kategori: 'kementerian',
    status: 'terdaftar',
    tahun: '2024',
    updatedAt: new Date().toISOString(),
    notes: 'Kemenkes RI - Tenaga Kesehatan & Dokter Spesialis',
  },
  {
    id: 'instansi-bkn',
    nama: 'Badan Kepegawaian Negara',
    kode: '1008',
    kategori: 'lembaga',
    status: 'terdaftar',
    tahun: '2024',
    updatedAt: new Date().toISOString(),
    notes: 'BKN Pusat & Kantor Regional',
  },
  {
    id: 'instansi-pemprov-dki',
    nama: 'Pemerintah Provinsi DKI Jakarta',
    kode: '6100',
    kategori: 'pemprov',
    provinsi: 'DKI Jakarta',
    status: 'terdaftar',
    tahun: '2024',
    updatedAt: new Date().toISOString(),
    notes: 'Pemprov DKI Jakarta',
  },
  {
    id: 'instansi-pemkab-banyuwangi',
    nama: 'Pemerintah Kabupaten Banyuwangi',
    kode: '6511',
    kategori: 'pemkab_pemkot',
    provinsi: 'Jawa Timur',
    status: 'terdaftar',
    tahun: '2024',
    updatedAt: new Date().toISOString(),
    parsedData: {
      meta: {
        docTitle: 'PANITIA SELEKSI NASIONAL PENGADAAN CASN 2024 - HASIL INTEGRASI SKD DAN SKB',
        tahun: '2024',
        parsedAt: new Date().toISOString(),
        sourceType: 'sample',
        fileName: 'HASIL_INTEGRASI_CPNS_BANYUWANGI_2024.pdf',
        totalFormasiCount: 1,
        totalPesertaCount: 2,
      },
      formasiList: [
        {
          id: 'banyuwangi-1',
          header: {
            instansi: '6511 - Pemerintah Kab. Banyuwangi',
            kodeInstansi: '6511',
            namaInstansi: 'Pemerintah Kab. Banyuwangi',
            jabatanFormasi: 'JF0017705 - POLISI PAMONG PRAJA AHLI PERTAMA',
            kodeJabatan: 'JF0017705',
            namaJabatan: 'POLISI PAMONG PRAJA AHLI PERTAMA',
            lokasiFormasi: '65110142 - Satuan Polisi Pamong Praja',
            kodeLokasi: '65110142',
            namaLokasi: 'Satuan Polisi Pamong Praja',
            jenisFormasi: '1 - UMUM',
            kodeJenisFormasi: '1',
            namaJenisFormasi: 'UMUM',
            pendidikan: 'S-1 SATUAN POLISI PAMONG PRAJA / S-1 HUKUM / S-1 ILMU PEMERINTAHAN',
            jumlahKuota: 3,
            kuotaPendidikan: 3,
            kuotaJenisFormasi: 3,
            kuotaLokasi: 3,
            kuotaJabatan: 3,
            kuotaInstansi: 3,
            kuotaPerTingkat: {
              pendidikanCount: 3,
              jenisCount: 3,
              lokasiCount: 3,
              jabatanCount: 3,
              instansiCount: 3,
            },
          },
          pesertaList: [
            {
              no: 1,
              noPeserta: '24651120110000101',
              nama: 'ACHMAD RIFADIN',
              tanggalLahir: '14 Mei 1997',
              pendidikan: 'S-1 ILMU PEMERINTAHAN',
              ipk: 3.75,
              twk: 115,
              tiu: 140,
              tkp: 192,
              totalSkd: 447,
              skorSkd: 32.509,
              skb: 76.0,
              skorSkb: 45.6,
              nilaiAkhir: 78.109,
              keterangan: 'P/L',
            },
            {
              no: 2,
              noPeserta: '24651120120000188',
              nama: 'DIANA RETNO WULAN',
              tanggalLahir: '22 Agustus 1999',
              pendidikan: 'S-1 HUKUM',
              ipk: 3.68,
              twk: 110,
              tiu: 135,
              tkp: 188,
              totalSkd: 433,
              skorSkd: 31.491,
              skb: 72.0,
              skorSkb: 43.2,
              nilaiAkhir: 74.691,
              keterangan: 'P/L',
            },
          ],
          verification: {
            isValid: true,
            scoreAccuracyPercent: 100,
            totalRecords: 2,
            discrepanciesCount: 0,
            passedCount: 2,
            failedCount: 0,
            discrepanciesList: [],
          },
        },
      ],
      header: {
        instansi: '6511 - Pemerintah Kab. Banyuwangi',
        jabatanFormasi: 'JF0017705 - POLISI PAMONG PRAJA AHLI PERTAMA',
        lokasiFormasi: '65110142 - Satuan Polisi Pamong Praja',
        jenisFormasi: '1 - UMUM',
        pendidikan: 'S-1 SATUAN POLISI PAMONG PRAJA / S-1 HUKUM / S-1 ILMU PEMERINTAHAN',
        jumlahKuota: 3,
        kuotaPendidikan: 3,
        kuotaJenisFormasi: 3,
        kuotaLokasi: 3,
        kuotaJabatan: 3,
        kuotaInstansi: 3,
      },
      pesertaList: [
        {
          no: 1,
          noPeserta: '24651120110000101',
          nama: 'ACHMAD RIFADIN',
          tanggalLahir: '14 Mei 1997',
          pendidikan: 'S-1 ILMU PEMERINTAHAN',
          ipk: 3.75,
          twk: 115,
          tiu: 140,
          tkp: 192,
          totalSkd: 447,
          skorSkd: 32.509,
          skb: 76.0,
          skorSkb: 45.6,
          nilaiAkhir: 78.109,
          keterangan: 'P/L',
        },
        {
          no: 2,
          noPeserta: '24651120120000188',
          nama: 'DIANA RETNO WULAN',
          tanggalLahir: '22 Agustus 1999',
          pendidikan: 'S-1 HUKUM',
          ipk: 3.68,
          twk: 110,
          tiu: 135,
          tkp: 188,
          totalSkd: 433,
          skorSkd: 31.491,
          skb: 72.0,
          skorSkb: 43.2,
          nilaiAkhir: 74.691,
          keterangan: 'P/L',
        },
      ],
      verification: {
        isValid: true,
        scoreAccuracyPercent: 100,
        totalRecords: 2,
        discrepanciesCount: 0,
        passedCount: 2,
        failedCount: 0,
        discrepanciesList: [],
      },
    },
    pdfFileName: 'HASIL_INTEGRASI_CPNS_BANYUWANGI_2024.pdf',
    notes: 'Pemkab Banyuwangi - JF0017705 Polisi Pamong Praja Ahli Pertama (Kuota: 3, Peserta: 2 - 1 Slot Kosong)',
  },
];
